/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#4edea3',
        'on-error-container': '#93000a',
        'surface-container-low': '#f3f3fd',
        'on-tertiary': '#ffffff',
        'background': '#faf8ff',
        'on-primary-container': '#c4d2ff',
        'surface-dim': '#d9d9e4',
        'on-primary': '#ffffff',
        'primary-fixed': '#dae2ff',
        'inverse-on-surface': '#f0f0fb',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#005236',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#002113',
        'on-primary-fixed-variant': '#0040a2',
        'primary': '#003d9b',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#380d00',
        'on-secondary-container': '#00714d',
        'on-primary-fixed': '#001848',
        'tertiary-fixed': '#ffdbcf',
        'surface-bright': '#faf8ff',
        'surface-tint': '#0c56d0',
        'outline-variant': '#c3c6d6',
        'inverse-primary': '#b2c5ff',
        'on-surface': '#191b23',
        'primary-container': '#0052cc',
        'surface-container-high': '#e7e7f2',
        'tertiary-container': '#a33500',
        'secondary-container': '#6cf8bb',
        'surface-variant': '#e1e2ec',
        'secondary': '#006c49',
        'error': '#ba1a1a',
        'surface': '#faf8ff',
        'on-tertiary-fixed-variant': '#812800',
        'surface-container-highest': '#e1e2ec',
        'on-surface-variant': '#434654',
        'on-tertiary-container': '#ffc6b2',
        'tertiary-fixed-dim': '#ffb59b',
        'tertiary': '#7b2600',
        'primary-fixed-dim': '#b2c5ff',
        'on-background': '#191b23',
        'outline': '#737685',
        'secondary-fixed': '#6ffbbe',
        'inverse-surface': '#2e3038',
        'surface-container': '#ededf8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        xl: '32px',
        lg: '24px',
        sm: '8px',
        unit: '4px',
        gutter: '16px',
        margin: '24px',
        md: '16px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'h2': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'table-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'h1': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
